# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
